apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: geoserver
  annotations:
    nginx.ingress.kubernetes.io/app-root: /geoserver
spec:
  tls:
  - hosts:
    - geoserver.domain.ndslabs.org
    secretName: ndslabs-tls-secret
  rules:
  - host: geoserver.domain.ndslabs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: geoserver
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: geoserver
  labels:
    component: geoserver
spec:
  selector:
    component: geoserver
  ports:
    - port: 8080
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: geoserver
spec:
  replicas: 1
  selector:
    component: geoserver
  template:
    metadata:
      labels:
        component: geoserver
    spec:
      containers:
      - name: geoserver
        image: kartoza/geoserver
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: "/opt/geoserver/data_dir"
        env:
          - name: GEOSERVER_DATA_DIR
            value: "/opt/geoserver/data_dir"
        resources:
          limits:
            cpu: 1000m
            memory: 8G
          requests:
            cpu: 100m
            memory: 100M
      volumes:
       - hostPath:
            path: "/mnt/shared/geoserver/"
         name: data
      nodeSelector:
          ndslabs-role-compute: "true"
