apiVersion: v1
kind: Service
metadata:
  name: bety
  labels:
    component: bety
spec:
  selector:
    component: bety
  ports:
    - port: 5432
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: bety
spec:
  replicas: 1
  selector:
    component: bety
  template:
    metadata:
      labels:
        component: bety
    spec:
      containers:
      - name: bety
        image: terraref/bety-postgis
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: "/var/lib/postgresql/data"
        env:
          - name: POSTGRES_DB
            value: "bety"
        resources:
          limits:
            cpu: 1000m
            memory: 8G
          requests:
            cpu: 100m
            memory: 100M
      volumes:
      - name: data
        emptyDir: {}
      nodeSelector:
          ndslabs-role-compute: "true"
